### ISSUE TITLE
human is allowed to cheat

### ISSUE THREAD

**Issue by narimiran** [memoiry/Ticky#1]
Human is allowed to play over bot's move (changing bot's already placed X to player's O) and win the game.

![tricky_01](https://cloud.githubusercontent.com/assets/16516130/24138219/ac21f43e-0e17-11e7-91aa-3d7d5480d23e.PNG)
![tricky_02](https://cloud.githubusercontent.com/assets/16516130/24138220/ac37a72a-0e17-11e7-9914-135f81366903.PNG)
![tricky_03](https://cloud.githubusercontent.com/assets/16516130/24138221/ac44c284-0e17-11e7-9d53-bb78f741a2cf.PNG)

**Comment by memoiry** [comment]
👍  Yes, I have forgotten to check the legality of the movement. 

I have fixed it, you can try again : )

**Comment by narimiran** [comment]
Fixed!
